name: pyicenv
channels:
  - litex-hub
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10.*
  - ipykernel
  - jupyterlab
  - conda-forge::ngspice
  - xschem
  - xtermcolor
  - magic
  - netgen
